---
extends: default
ignore:
  - modules/template/templates/cloud-config.yaml
  - tests/fixtures/root/templates/runtime-init-config.yaml
  - tests/fixtures/stateless/templates/runtime-init-config.yaml
rules:
  line-length:
    max: 120
